name: PlatformIO CI

on: [push]

jobs:
  build_and_check:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio

    - uses: actions/checkout@v2
    - name: PlatformIO Run
      run: |
        cd firmware
        pio run
    - name: Upload firmware
      uses: actions/upload-artifact@v3
      with:
        name: firmware
        path: firmware/.pio/build/S57Bv2/firmware.bin

    - uses: actions/checkout@v2
    - name: PlatformIO Check
      run: |
        cd firmware
        echo "${{ secrets.MISRA_TEXT }}" > misra_rules_set_cppcheck.txt
        cat misra_rules_set_cppcheck.txt
        pio check --fail-on-defect high > report.txt
    - name: Upload report
      uses: actions/upload-artifact@v3
      with:
        name: pio check report
        path: firmware/report.txt
